spring:
  application:
    name: shop-app
  http:
    encoding:
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/public/

  profiles.active: ${env:local}
  oracle:
    datasource:
      driverClassName: oracle.jdbc.driver.OracleDriver
      connectionTestQuery: SELECT 1 FROM DUAL
      maximumPoolSize: 3
  mysql:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1 FROM DUAL
      maxActive: 5
      maxAge: 1
      minIdle: 1
      maxIdle: 5
      maximumPoolSize: 5

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: kr.co.oliveyoung.feature
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false
    default-statement-timeout: 30
    map-underscore-to-camel-case: true


server:
  port: ${PORT:9090}
  compression:
    enabled: true

logging:
  config: classpath:config/logback-config.xml

---
spring:
  profiles: local
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T
---
spring:
  profiles: dev
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T
---
spring:
  profiles: test
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T
---
spring:
  profiles: beta
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T
---
spring:
  profiles: stage
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T
---
spring:
  profiles: production
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
      username: OOMAPP
      password: TAblet52()
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://116.121.31.99:3306/tablet_app?socketTimeout=30000&amp;connectTimeout=30000
      username: tabletAdmin
      password: 1q2w3e4r%T