export enum ImageType {
  // 브랜드로고화이트
  BRAND_LOGO_WHITE = 'BRAND_LOGO_WHITE',
  // 브랜드로고블랙
  BRAND_LOGO_BLACK = 'BRAND_LOGO_BLACK',
  // 스토어뷰Image.
  STOREVIEW_IMAGE = 'STOREVIEW_IMAGE',
  // 상점상품Image.
  STORE_PRODUCT_IMAGE = 'STORE_PRODUCT_IMAGE',
  // 신상품레이아웃Image.
  NEW_ITEM_LAYOUT_IMAGE = 'NEW_ITEM_LAYOUT_IMAGE',
  // 스토어NEWSImage
  STORE_NEWS = 'STORE_NEWS',
  SALE_EVENT = 'SALE_EVENT',
  // 단일상품이미지
  PRODUCT = 'PRODUCT',
  // 심사자료
  JOIN_INSPECTION_IMAGE = 'JOIN_INSPECTION_IMAGE',
  // 사업자등록증
  BUSINESS_NO = 'BUSINESS_NO',
  // 통신판매업신고증
  COMMUNICATION_SALE_NO = 'COMMUNICATION_SALE_NO',
  // 브랜드계약
  BRAND_MANAGE_LICENSE = 'BRAND_MANAGE_LICENSE',
  CLOUD_IMAGE = 'CLOUD_IMAGE',
  FRESH_ITEM = 'FRESH_ITEM',
  THEME_CONTENTS = 'THEME_CONTENTS',
  BARCODE = 'BARCODE',
  SPECIAL_LIST_IMAGE = 'SPECIAL_LIST_IMAGE',
  SPECIAL_HOME_BANNER = 'SPECIAL_HOME_BANNER',
  SERVICE_NEWS_BANNER = 'SERVICE_NEWS_BANNER',
  SERVICE_BANNER = 'SERVICE_BANNER',
  USER_DEFINITION = 'USER_DEFINITION',

  /**
   * 지점관련
   * */
  MALL_PC_REPRESENTATIVE = 'MALL_PC_REPRESENTATIVE',
  MALL_MOBILE_REPRESENTATIVE = 'MALL_MOBILE_REPRESENTATIVE',
  MALL_LOGO = 'MALL_LOGO',

  /**
   * 스토어 관련
   ****/
  // 스토어 로고이미지
  BELONG_STORE_LOGO = 'BELONG_STORE_LOGO',
  // 스토어대표이미지  매장내 외부 전경으로 사용
  BELONG_STORE_REPRESENTATIVE = 'BELONG_STORE_REPRESENTATIVE',
  LIST_A = 'LIST_A',
  LIST_B = 'LIST_B',
  BRAND_LIST = 'BRAND_LIST',
  STORE_INNER_FRONT = 'STORE_INNER_FRONT',
  STORE_INNER_LEFT = 'STORE_INNER_LEFT',
  STORE_INNER_RIGHT = 'STORE_INNER_RIGHT',
  STORE_ENTRANCE = 'STORE_ENTRANCE',
  PRODUCT_LIST = 'PRODUCT_LIST',
  SEARCH_QUERY_KEYWORD = 'SEARCH_QUERY_KEYWORD',
  BRAND_MOBILE_HOME_1 = 'BRAND_MOBILE_HOME_1',
  BRAND_MOBILE_HOME_2 = 'BRAND_MOBILE_HOME_2',
  BRAND_MOBILE_HOME_3 = 'BRAND_MOBILE_HOME_3',
  BRAND_PC_HOME_1 = 'BRAND_PC_HOME_1',
  BRAND_PC_HOME_2 = 'BRAND_PC_HOME_2',
  BRAND_TRPC_LOGO = 'BRAND_TRPC_LOGO',
  MY_PET = 'MY_PET',
  PET_KIND = 'PET_KIND',
  SE3_EXTRACT_IMAGE = 'SE3_EXTRACT_IMAGE',
}
